poolMaxTotal: 500
poolMaxIdle: 5
connectionTimeout: 2000
soTimeout: 2000
maxRedirections: 6
timeBetweenEvictionRunsMillis: 30000
minEvictableIdleTimeMillis: 1800000
softMinEvictableIdleTimeMillis: 1800000
maxWaitMillis: 60000
testOnBorrow: true
testWhileIdle: false
testOnReturn: false
nodes:
  - ip: 127.0.0.1
    port: 7000
  - ip: 127.0.0.1
    port: 7001
  - ip: 127.0.0.1
    port: 7002

