id: 1
ip: 127.0.0.1
port: 8001
httpPort: 9000
type: 1
name: 网关1服
orderedThreadPoolExecutorSize: 50
receiveBufferSize: 1048576
sendBufferSize: 1048576
reuseAddress: true
tcpNoDelay: true
readerIdleTime: 180
writerIdleTime: 0
soLinger: 0
channel: 37wan