id: 2
receiveBufferSize: 1048576
sendBufferSize: 1048576
orderedThreadPoolExecutorSize: 10
soLinger: 0
type: 1
name: 大厅2服
maxConnectCount: 3
connTo:
  receiveBufferSize: 1048576
  sendBufferSize: 1048576
  type: 7
  host: 127.0.0.1
  port: 8520