id: 1
receiveBufferSize: 1048576
sendBufferSize: 1048576
orderedThreadPoolExecutorSize: 2
soLinger: 0
type: 7
maxConnectCount: 1
connTo:
  receiveBufferSize: 1048576
  sendBufferSize: 1048576
  type: 3
  host: 127.0.0.1
  port: 8000