id: 3
ip: 127.0.0.1
port: 8000
httpPort: 9000
type: 7
orderedThreadPoolExecutorSize: 300
receiveBufferSize: 1048576
sendBufferSize: 1048576
reuseAddress: true
tcpNoDelay: true
readerIdleTime: 180
writerIdleTime: 0
soLinger: 0
channel: jzy