id: 1
ip: 127.0.0.1
port: 6000
httpPort: 6000
type: 1
name: 网关1服
orderedThreadPoolExecutorSize: 100
receiveBufferSize: 1048576
sendBufferSize: 1048576
reuseAddress: true
tcpNoDelay: true
readerIdleTime: 1800
writerIdleTime: 1800
soLinger: 0
channel: jzy
