minaServerConfig:
  id: ${GATE.ID}
  ip: ${GATE.HOST}
  port: ${GATE.GMAE.PORT}
  httpPort: ${GATE.GMAE.PORT}
  type: GATE
  name: 网关 ${GATE.ID}服
  orderedThreadPoolExecutorSize: 50
  receiveBufferSize: 1048576
  sendBufferSize: 1048576
  reuseAddress: true
  tcpNoDelay: true
  readerIdleTime: 180
  writerIdleTime: 0
  soLinger: 0
  channel: 37wan