id: 1
ip: 127.0.0.1
port: 5040
httpPort: 5041
type: 1
name: 网关1服
orderedThreadPoolExecutorSize: 50
receiveBufferSize: 1048576
sendBufferSize: 1048576
reuseAddress: true
tcpNoDelay: true
readerIdleTime: 600
writerIdleTime: 600
soLinger: 0
channel: jzy
