nettyClientConfig:
  id: ${GAME.ID}
  receiveBufferSize: 1048576
  sendBufferSize: 1048576
  type: GAME_BYDR
  name: 捕鱼达人 ${GAME.ID}服
  maxConnectCount: 10
  ip: ${GAME.CONNTO.HALL.HOST}
  groupThreadNum: 10
  port: 8520
  info: NettyFirst
